CC = gcc

all: euler

problem1: problem1.o 

problem1.o: problem1.c

problem2: problem2.o

problem2.o: problem2.c

problem3: problem3.o

problem3.o: problem3.c problem3.h

clean:
	rm -rf *.o euler
	rm -rf *.o problem1
	rm -rf *.o problem2
	rm -rf *.o problem3